defaults:
  - model: cnn
  - optimizer: adam

dataset:
  name: data
  path: /mnt/c/Users/Sirine/Documents/data
  test_size: 0.2
  val_size: 0.1


training:
  resize: 128
  epochs: 10
  batch_size: 32
